hyperparameters:
  epochs: 2
  batch_size: 4

  lr: 0.001
  momentum: 0.9 

  num_workers: 8

paths:
  train_dir: 'data/cifar10/train'
  test_dir: 'data/cifar10/test'
  model_path: 'weights/checkpoint.pth'